version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: me_nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/http.d:/etc/nginx/conf.d
    depends_on:
      - next
      - backend
    restart: always

  next:
    build: ./project/frontend
    container_name: me_next
    expose:
      - "3000"
    environment:
    - HOSTNAME=0.0.0.0
    # - PORT=7571
    restart: always

  backend:
    build: ./project/backend
    container_name: me_backend
    expose:
      - "5000"
    restart: always
