version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: me_nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/http.d:/etc/nginx/conf.d
    depends_on:
      - next
      - backend
    restart: always

  next:
    build: ./project/frontend
    container_name: me_next
    expose:
      - "3000"
    environment:
    - HOSTNAME=0.0.0.0
    # - PORT=7571
    restart: always

  backend:
    build: ./project/backend
    container_name: me_backend
    expose:
      - "5000"
    restart: always


# version: '3.9'

# services:
#   app:
#     environment:
#       - TZ=Asia/Bangkok
#       - DB_SERVER=mssql
#       - DB_PORT=1433
#       - DB_USER=sa
#       - DB_PASSWORD=k5L9JmmEzzP65udoT5T5Iguq
#       - DB_NAME=ME_DB
#     build: .
#     container_name: me_app
#     volumes:
#       - ./project/backend:/app
#       - ./project/backend/node_modules:/app/node_modules
#       - ./project/frontend:/app/frontend
#       - ./project/frontend/node_modules:/app/frontend/node_modules
#       - ./nginx/http.d/:/etc/nginx/http.d/
#     ports:
#       - '3000:80'
#     depends_on:
#       mssql:
#         condition: service_healthy
#     restart: always

#   mssql:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: me_database
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=k5L9JmmEzzP65udoT5T5Iguq
#       - MSSQL_PID=Express
#     ports:
#       - "1433:1433"
#     volumes:
#       - mssql_data:/var/opt/mssql
#     healthcheck:
#       test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P k5L9JmmEzzP65udoT5T5Iguq -Q "SELECT 1"
#       interval: 10s
#       timeout: 5s
#       retries: 10
#     restart: always

# volumes:
#   mssql_data:


  