CREATE DATABASE QMED_LOG COLLATE Thai_CI_AS;

USE QMED_LOG;

DROP TABLE IF EXISTS [dbo].[medlog];

CREATE TABLE [dbo].[medlog] (
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [AN] VARCHAR(20) NOT NULL,
    [CreateAt] DATETIME DEFAULT GETDATE(),
);