CREATE DATABASE ME_DB COLLATE Thai_CI_AS;

USE ME_DB;

Drop TABLE IF EXISTS [dbo].[Users];

CREATE TABLE [dbo].[Users] (
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [UserId] NVARCHAR(50) NOT NULL UNIQUE,
    [Name] NVARCHAR(50) DEFAULT NULL,
    [UserType] INT NOT NULL DEFAULT 1,
    [Role] INT NOT NULL DEFAULT 1,
    [Password] NVARCHAR(255) NOT NULL,
    [CreateAt] DATETIME DEFAULT GETDATE(),
    [UpdateAt] DATETIME DEFAULT GETDATE(),
    [DeleteAt] DATETIME DEFAULT NULL,
);

INSERT INTO [dbo].[Users] ([UserId],[Name],[Password],[Role],[UserType])
VALUES
('000000','admin','$2a$12$53PPHaeHhJeOS59Y1742LuZXX1BwE0fQ9oxYCI/0GGs1RqNFraBEu',3,1);
